<?php

/**
 * AdNonPsychoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdNonPsychoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdNonPsychoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdNonPsycho');
    }
}