<?php

/**
 * AdNotificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdNotificationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdNotificationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdNotification');
    }
}