<?php

/**
 * AdNonPsychoPatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdNonPsychoPatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdNonPsychoPatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdNonPsychoPat');
    }
}