<?php

/**
 * AdPatient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    GuizMed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AdPatient extends BaseAdPatient
{
  public function getPrescriptions($id)
  {
    $q = Doctrine_Query::create()
    ->from('AdPrescription p')
    ->where('p.user_patient_id = ?', $id);
return $q->execute();
  }
  public function getNonPsycho(){
      return Doctrine_Query::create()->from('AdNonPsychoPat npp')->where('npp.ad_patient_id = ?',$this->getPatientId())->execute();
  }
}