<?php

/**
 * AdUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    GuizMed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AdUser extends BaseAdUser
{
    function inlog($uName,$pWord)
    {
       $users = Doctrine_Query::create()->from('AdUser au')->where('au.uname = ?', $uName)->execute();
       if($users[0]->getPassw()==$pWord){
            return $this->createToken($users[0]->getUserId());
       }else{
           return "Failed";
       }
    }
    function unlock($token,$unlock)
    {
       $users = Doctrine_Query::create()->from('AdUser au')->where('au.token = ?', $token)->execute();
       if($users[0]->getUnlockCode()==$unlock){
            return 'true';
       }else{
           return "false";
       }
    }
    function firstLogin($uName,$old,$new,$unlock)
    {
       $users = Doctrine_Query::create()->from('AdUser au')->where('au.uName = ?', $uName)->execute();
       if($users[0]->getUnlockCode()==$unlock && $users[0]->getPassw()==$old){
           $users[0]->setPassw($new);
           $users[0]->save();
           return 'true';
       }else{
           return "false";
       }
    }
      function createToken($id)
    {
        $users = Doctrine_Query::create()->from('AdUser au')->where('au.user_id = ?',$id)->execute();
        $user = $users[0];
        $token = $user->getFname().$user->getLname();
        $user->setToken($token);
        $user->save();

        return $token;
    }
    function isAllowed($token){
        $users = Doctrine_Query::create()->from('AdUser au')->where('au.token = ? ', $token)->execute();
        if($users->count()>0){
            return true;
        }else{
            return false;
        }
    }    
}