<?php

/**
 * IntMetabolism
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    GuizMed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class IntMetabolism extends BaseIntMetabolism
{
    function getDrugs(){
        $q = Doctrine_Query::create()->from('intDrug id')->where('id.int_enzym_id = ?', $this->getEnzymGroupId());
        return $q->execute();
    }
}